Test video feed


In [2]:
import cv2
cap=cv2.VideoCapture(0)

while True:
    ret,frame=cap.read()

    if not ret:
        break
    cv2.imshow('video feed',frame)
    
    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


[ WARN:0@6720.962] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@6721.166] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range


Detect Face

In [2]:

cap=cv2.VideoCapture(0)

face_detector=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')

while True:
    ret,frame=cap.read()
    if not ret:
        break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_detector.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=5)

    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
    cv2.imshow('video feed',frame)

    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

[ WARN:0@28.859] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@28.859] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range


In [ ]:
def verify_image(image_path, present_embeddings):
    
    cap=cv2.VideoCapture(0)

    face_detector=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')

    while True:
        ret,frame=cap.read()
        if not ret:
            break
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        faces=face_detector.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=5)
        faces=cv2.resize(faces,160,160)

        for (x,y,w,h) in faces:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)

        cv2.imshow('video feed',frame)

        if cv2.waitKey(1)==ord('q'):
            break

   
        
    # Assuming image is already 160x160 cropped face
    claim_embedding= get_embedding(frame)
    print(claim_embedding)
    # Compare to present embeddings
    min_dist = float('inf')
    for i,present_embedding in enumerate(present_embeddings):
        dist = np.linalg.norm(claim_embedding - present_embedding)
        print(f'distance to embedding {i} is {dist}')
        if dist < min_dist:
            min_dist = dist
    
    result = "Present" if min_dist < 1 else "Not Present"
    print(f'minimum distanc {min_dist}')
    print(result)
    
   
    cv2.rectangle(frame, (0, 0), (160, 160), (0, 255, 0), 2)  
    cv2.putText(frame, result, (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
    cv2.imshow("Verification Result", frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


present_folder = 'Tdataset'
present_embeddings = create_embedding(present_folder)
print(f"Total embeddings: {len(present_embeddings)}")
image_path = ['cropped_dataset/p/jafer/20240419_180120_face3007.jpg',]

for i in image_path:
    verify_image(i, present_embeddings)


Crop Face to be appropriate for facenet model 160X160

In [3]:
import os

os.chdir('/home/cs/Desktop/Project/Computer_Vision_Based_Attendance')

In [8]:
import os

face_detector=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')
input_dir='dataset'
output_dir='cropped_dataset'


if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for person in os.listdir(input_dir):
    person_input=os.path.join(input_dir,person)
    person_output=os.path.join(output_dir,person)

    
    
    for img_file in os.listdir(person_input):
        img_path=os.path.join(person_input,img_file)
        img=cv2.imread(img_path)
        gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

        face=face_detector.detectMultiScale(gray,1.1,5)
        if len(face)>0:
            x,y,w,h = face[0]
            face=img[y:y+h,x:x+w]
            face=cv2.resize(face,(160,160))
            output_path=os.path.join(person_output,img_file)
            cv2.imwrite(output_path,face)
print('face cropped')

NotADirectoryError: [Errno 20] Not a directory: 'dataset/main.py'

In [17]:
import os

In [ ]:
import os
import cv2


face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')


input_dir = 'dataset'
output_dir = 'cropped_dataset'


if not os.path.exists(output_dir):
    os.makedirs(output_dir)


for person in os.listdir(input_dir):
    person_input = os.path.join(input_dir, person)
    

    if not os.path.isdir(person_input):
        continue

    person_output = os.path.join(output_dir, person)

    
    if not os.path.exists(person_output):
        os.makedirs(person_output)

    # Loop through each image file for that person
    for img_file in os.listdir(person_input):
        img_path = os.path.join(person_input, img_file)

        # Check if the current item is a file
        if not os.path.isfile(img_path):
            continue

        img = cv2.imread(img_path)

       
        if img is None:
            print(f"Skipping {img_file} as it cannot be read.")
            continue

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Detect faces in the image
        faces = face_detector.detectMultiScale(gray, 1.1, 5)

        # If faces are detected, crop and save them
        if len(faces) > 0:
            x, y, w, h = faces[0]
            face = img[y:y + h, x:x + w]
            face = cv2.resize(face, (160, 160))  # Resize the face to 160x160
            output_path = os.path.join(person_output, img_file)
            cv2.imwrite(output_path, face)
        else:
            print(f"No face detected in {img_file}, skipping.")

print('Face cropping process completed.')


Face cropping process completed.


In [2]:
pip install mtcnn

Defaulting to user installation because normal site-packages is not writeable
  Using cached mtcnn-0.1.1-py3-none-any.whl.metadata (5.8 kB)
Using cached mtcnn-0.1.1-py3-none-any.whl (2.3 MB)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Crop face from group image

In [1]:
import os
import cv2

# Load the Haar Cascade face detector
face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Define input and output directories
input_dir = 'dataset'
output_dir = 'cropped_dataset'

# Create the output directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Loop through each person in the input directory
for person in os.listdir(input_dir):
    person_input = os.path.join(input_dir, person)

    # Skip if it's not a directory (e.g., it's a file like main.py)
    if not os.path.isdir(person_input):
        continue

    person_output = os.path.join(output_dir, person)

    # Create the person's output directory if it doesn't exist
    if not os.path.exists(person_output):
        os.makedirs(person_output)

    # Loop through each image file for that person
    for img_file in os.listdir(person_input):
        img_path = os.path.join(person_input, img_file)

        # Check if the current item is a file
        if not os.path.isfile(img_path):
            continue

        img = cv2.imread(img_path)

        # Check if the image was loaded successfully
        if img is None:
            print(f"Skipping {img_file} as it cannot be read.")
            continue

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Detect faces in the image (this detects multiple faces)
        faces = face_detector.detectMultiScale(gray, 1.1, 5)

        # If faces are detected, crop and save them
        if len(faces) > 0:
            for i, (x, y, w, h) in enumerate(faces):
                face = img[y:y + h, x:x + w]  # Crop the face region
                face = cv2.resize(face, (160, 160))  # Resize the face to 160x160

                # Save each cropped face with a unique name
                output_path = os.path.join(person_output, f"{img_file.split('.')[0]}_face{i+1}.jpg")
                cv2.imwrite(output_path, face)
        else:
            print(f"No faces detected in {img_file}, skipping.")

print('Face cropping process completed.')


KeyboardInterrupt: 

Better way to crop face from group image uscin mtcnn

In [ ]:
import os
import cv2
from mtcnn import MTCNN


detector = MTCNN()


input_dir = 'dataset/f'  
output_dir = 'cropped_dataset/feleke'  

if not os.path.exists(output_dir):
    os.makedirs(output_dir)


for person in os.listdir(input_dir):
    person_input = os.path.join(input_dir, person)

    
    if not os.path.isdir(person_input):
        continue

    person_output = os.path.join(output_dir, person)

    
    if not os.path.exists(person_output):
        os.makedirs(person_output)

    
    for img_file in os.listdir(person_input):
        img_path = os.path.join(person_input, img_file)

        
        if not os.path.isfile(img_path):
            continue

        img = cv2.imread(img_path)

        
        if img is None:
            print(f"Skipping {img_file} as it cannot be read.")
            continue

        # Detect faces using MTCNN
        faces = detector.detect_faces(img)

        # If faces are detected, crop and save them
        if len(faces) > 0:
            for i, face in enumerate(faces):
                x, y, w, h = face['box']  # Get the face coordinates
                face_img = img[y:y + h, x:x + w]  # Crop the face
                face_img = cv2.resize(face_img, (160, 160))  # Resize the face to 160x160

                
                output_path = os.path.join(person_output, f"{img_file.split('.')[0]}_face{i}.jpg")
                cv2.imwrite(output_path, face_img)
        else:
            print(f"No faces detected in {img_file}, skipping.")

print('Face cropping process completed.')


2025-03-10 14:51:50.938989: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 17587360 exceeds 10% of free system memory.
2025-03-10 14:51:52.101248: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 17587360 exceeds 10% of free system memory.
2025-03-10 14:51:52.112381: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 17587360 exceeds 10% of free system memory.
2025-03-10 14:51:52.444130: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 13728896 exceeds 10% of free system memory.
2025-03-10 14:51:52.474224: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 13728896 exceeds 10% of free system memory.


1/1 [==============================] - 0s 35ms/step
Face cropping process completed.


In [1]:
import tensorflow as tf
import numpy as np

model='20180402-114759.pb'
with tf.Graph().as_default():
    with open(model,'rb') as f:
        graph_def=tf.compat.v1.GraphDef.FromString(f.read())
    tf.import_graph_def(graph_def,name='')
session = tf.compat.v1.Session()
images_input = session.graph.get_tensor_by_name("input:0")
embeddings_output = session.graph.get_tensor_by_name("embeddings:0")
phase_train = session.graph.get_tensor_by_name("phase_train:0")

2025-03-10 22:37:32.658440: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-10 22:37:54.676540: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-10 22:37:54.766131: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-10 22:38:20.802561: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."

In [ ]:
import tensorflow.compat.v1 as tf
import cv2
tf.disable_v2_behavior()

# Load the FaceNet model and graph
with tf.gfile.GFile('20180402-114759.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

# Load the graph
with tf.Graph().as_default() as graph:
    tf.import_graph_def(graph_def, name='')
    session = tf.compat.v1.Session(graph=graph)

    # Access the input/output tensors
    images_input = session.graph.get_tensor_by_name("input:0")
    embeddings_output = session.graph.get_tensor_by_name("embeddings:0")
    phase_train = session.graph.get_tensor_by_name("phase_train:0")


2025-03-10 18:36:00.824575: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-10 18:36:06.911077: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-10 18:36:06.921927: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-10 18:36:19.309542: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
import os
import numpy as np


In [ ]:
def load_image(file_path):
    img=cv2.imread(file_path)
    return img

In [ ]:
def get_embedding(img):
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (160, 160))
    img = (img / 255.0 - 0.5) * 2.0
    img = np.expand_dims(img, axis=0)  

    embedding = session.run(tf.convert_to_tensor(embeddings_output, dtype=tf.float32), feed_dict={
        images_input: img,
        phase_train: False
    })
    

    if embedding.shape[0] == 1:
        print(f'em{embedding[0]}')
        return embedding[0]  
    else:
        return embedding[0, :]  

In [ ]:
def create_embedding(folder_path):
    face_detector=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')
    embeddings=[]

    for person in os.listdir(folder_path):
        person_path=os.path.join(folder_path,person)
        print(f'person path{person_path}')
        if os.path.isdir(person_path):
            person_embedding=[]
            for photo in os.listdir(person_path):
                photo_path=os.path.join(person_path,photo)
                print(f'photo path {photo_path}')
                img=load_image(photo_path)
                if img is None:
                    print(f'failed to load {photo_path}')
                gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
                faces=face_detector.detectMultiScale(gray,1.1,5)
                if len(faces)>0:
                    x,y,w,h=faces[0]
                    face=img[y:y+h,x:x+w]
                    print(face)
                    embedding=get_embedding(face)
                    print(embedding)
                    person_embedding.append(embedding)
                else:
                    print(f'No face in {photo_path}')
        if person_embedding:
            avg_embedding=np.mean(person_embedding,axis=0)
            embeddings.append(avg_embedding)
            print(f'embbeding created for {person}')
    return embeddings

folder_path='Tdataset'
embeddings_output=create_embedding(folder_path)
print(embeddings_output)

person pathTdataset/ezedin
photo path Tdataset/ezedin/20240419_181723_face11.jpg
No face in Tdataset/ezedin/20240419_181723_face11.jpg
photo path Tdataset/ezedin/20240419_181729_face18.jpg
No face in Tdataset/ezedin/20240419_181729_face18.jpg
photo path Tdataset/ezedin/20240419_181548_face9.jpg
No face in Tdataset/ezedin/20240419_181548_face9.jpg
photo path Tdataset/ezedin/photo_5841381442590987247_y_face3000.jpg
No face in Tdataset/ezedin/photo_5841381442590987247_y_face3000.jpg
photo path Tdataset/ezedin/photo_5841381442590987241_y_face3001.jpg
No face in Tdataset/ezedin/photo_5841381442590987241_y_face3001.jpg
photo path Tdataset/ezedin/photo_5841381442590987243_y_face3001.jpg
[[[ 5  2  4]
  [ 8  5  7]
  [ 8  6 12]
  ...
  [20 17 32]
  [16 14 26]
  [12  8 20]]

 [[ 7  4  6]
  [10  7  9]
  [10  8 14]
  ...
  [27 24 40]
  [22 19 34]
  [17 15 27]]

 [[ 9  6  8]
  [12  9 11]
  [12 11 15]
  ...
  [32 30 49]
  [29 26 42]
  [25 22 37]]

 ...

 [[30 19 15]
  [29 18 14]
  [28 17 13]
  ...
  

ValueError: Expected values [array([ 2.89695919e-03,  3.18879485e-02, -1.28320474e-02,  3.39371860e-02,
        1.75612438e-02, -3.90815660e-02,  3.97057980e-02,  4.16274890e-02,
        3.61470878e-02,  2.21980494e-02, -3.78015474e-03,  2.28695124e-02,
        1.03717241e-02,  5.88631704e-02,  1.36982156e-02,  4.32678126e-02,
       -6.22541420e-02, -1.70887029e-03, -1.66219641e-02, -8.23281892e-03,
       -1.61850583e-02,  2.11365167e-02, -6.87455153e-03,  3.01195253e-02,
        1.50323063e-02,  9.71998833e-03, -4.15421203e-02, -5.83968014e-02,
        5.53506520e-03, -6.85899034e-02, -2.41947956e-02,  2.60702614e-02,
        4.27013040e-02, -2.39843894e-02,  2.56103575e-02,  7.05552325e-02,
        4.02808823e-02,  2.46183537e-02, -1.66345909e-02,  9.78579652e-03,
       -2.41390765e-02,  4.12627170e-03,  1.52927497e-02, -3.95492800e-02,
       -5.46884388e-02,  2.65538041e-03, -1.90721937e-02,  9.70164835e-02,
       -2.36960296e-02,  3.99957299e-02,  3.68140335e-03, -1.61696859e-02,
       -3.46657517e-03, -1.63746271e-02,  6.14284677e-03, -4.98293899e-03,
        2.73337346e-02, -5.14815748e-03, -6.83565671e-03, -5.15636802e-02,
       -2.49233507e-02,  2.13412959e-02,  1.09345131e-02, -2.75825113e-02,
       -3.29032503e-02, -5.74533269e-02, -2.91821305e-02, -8.62850156e-03,
        7.93630779e-02,  1.09970141e-02,  8.76478851e-03, -2.54418496e-02,
       -2.59791985e-02, -1.04235644e-02,  3.53243090e-02, -2.18367074e-02,
        4.41136630e-03,  1.45749282e-02, -3.50475833e-02,  1.19830882e-02,
        1.87957585e-02,  9.29019693e-03, -4.05783020e-02, -2.84276530e-02,
       -3.16391513e-02,  1.37810754e-02,  5.99738881e-02, -1.59863532e-02,
       -6.29462674e-02, -4.46945243e-02, -1.66476648e-02,  4.57561426e-02,
       -1.58037234e-03, -3.73805873e-02,  3.60566378e-02,  1.88086666e-02,
       -6.24062493e-03, -7.93708116e-02, -5.99756166e-02,  5.11100031e-02,
       -9.37252957e-03,  1.81733798e-02, -4.29520337e-03, -2.56826915e-02,
       -3.27886529e-02, -4.64549325e-02,  3.61511926e-03,  5.87281073e-03,
        2.98140328e-02, -7.77882105e-03,  2.87754908e-02, -2.75784153e-02,
        1.27789602e-02, -3.49350236e-02, -1.36135705e-02, -4.86080460e-02,
        6.74386322e-02, -7.03620818e-03, -9.48451683e-02, -3.66738737e-02,
       -4.38300148e-02,  2.22600028e-02,  1.14469063e-02, -1.87984016e-02,
       -5.89051060e-02, -3.74487862e-02, -2.43069865e-02, -3.43066566e-02,
       -1.14358189e-02,  2.92643234e-02,  1.96071975e-02, -4.61514778e-02,
        2.67109144e-02, -3.91692594e-02, -2.00791303e-02,  5.38111590e-02,
        4.28654216e-02,  4.93394360e-02,  5.33478260e-02,  3.47269024e-03,
        6.30655736e-02, -8.39842297e-03,  3.84886973e-02, -3.20996391e-03,
        5.40837273e-02,  7.78591558e-02, -4.76905424e-03,  2.12560203e-02,
       -1.91755232e-03, -3.68543155e-02,  3.42477821e-02, -3.23948339e-02,
       -5.00271209e-02, -3.29872146e-02, -9.27393697e-03,  5.23488084e-03,
       -3.72368060e-02,  1.02508187e-01, -2.88456231e-02, -1.01088630e-02,
       -4.66212779e-02,  1.98341683e-02,  2.55992673e-02,  4.91483212e-02,
       -1.74089931e-02, -2.28577554e-02, -7.16546178e-02,  1.75709184e-02,
       -3.42724286e-02, -3.68709140e-03,  2.39852369e-02, -5.69706969e-02,
        1.63406823e-02,  2.52348650e-02,  7.91210756e-02, -3.02556250e-02,
       -2.05588806e-02, -1.95208099e-02, -5.22350594e-02,  5.51407598e-02,
       -8.63933861e-02, -8.89385585e-03, -8.62375647e-03, -6.47316352e-02,
        2.12008716e-04, -3.43275256e-02,  5.14917523e-02, -1.81898698e-02,
       -8.76583531e-03, -5.58184274e-03,  6.67489925e-03,  5.21218851e-02,
        5.39695658e-02, -1.02126028e-03, -1.68898888e-02,  3.72214727e-02,
       -3.54340747e-02, -1.24548376e-02, -5.00654533e-05,  2.24608299e-03,
       -4.04234370e-03,  4.32230681e-02,  2.33518984e-02,  7.47028753e-05,
        6.48844838e-02, -1.39587326e-02,  3.42781097e-02, -7.09843170e-03,
       -4.58154753e-02,  2.18684739e-03, -2.74995137e-02, -4.49547693e-02,
       -3.54112289e-03,  3.44382157e-03,  2.48244312e-02,  4.75647338e-02,
        5.20058274e-02, -6.31716847e-02,  1.22356620e-02, -1.89990103e-02,
       -1.47218781e-03, -1.07177636e-02,  1.20099317e-02,  1.91252101e-02,
        1.12374975e-04, -2.70408182e-03, -7.45131355e-03, -1.09640211e-02,
       -3.47146280e-02,  1.42147411e-02, -6.81156246e-03,  3.15370001e-02,
       -9.17443633e-03, -3.75276096e-02, -3.31423059e-02,  1.38956672e-02,
        7.14740390e-03,  5.40437698e-02,  3.39836217e-02, -3.84682417e-02,
       -5.42681143e-02, -4.04076576e-02,  3.30817029e-02, -1.42006828e-02,
        2.22322606e-02,  3.67055349e-02,  4.84682806e-02, -2.97102276e-02,
        2.63496395e-02,  5.77825531e-02, -2.83522997e-02, -4.68032658e-02,
       -1.92134883e-02,  6.15971908e-02, -5.10346377e-03, -3.37478286e-03,
       -6.27633259e-02,  2.04076320e-02, -1.80863962e-02,  3.74139026e-02,
        1.51602726e-03,  3.20106708e-02,  3.33191566e-02, -6.87842518e-02,
       -3.22034694e-02, -7.94674531e-02, -3.88049558e-02,  6.75892690e-03,
       -3.51273501e-03,  1.20969657e-02,  1.40473600e-02, -2.55538337e-02,
       -5.25989160e-02,  4.27393131e-02, -9.07556992e-03, -3.75652127e-02,
       -1.81264859e-02, -1.72210974e-03,  2.38428637e-02,  8.96345899e-02,
       -1.92063544e-02, -1.60212610e-02, -5.06913364e-02, -4.23652753e-02,
       -3.69334631e-02, -1.43858241e-02,  5.05667739e-03,  7.20459444e-04,
       -2.61706524e-02,  2.43567210e-02, -1.29517131e-02, -1.86693843e-03,
        4.96224053e-02,  4.10101563e-02, -8.67132377e-03, -5.38740940e-02,
       -4.26929593e-02, -3.55111286e-02, -2.78641954e-02,  1.47574395e-03,
       -5.74241281e-02, -3.12920264e-03,  1.30759543e-02,  3.32270041e-02,
        1.63439717e-02, -2.05890294e-02, -3.60945277e-02, -1.38229411e-03,
        1.93479732e-02, -1.16931824e-02, -1.41227981e-02,  5.16786389e-02,
       -2.20070165e-02,  3.86394560e-02,  1.06597794e-02,  7.90719613e-02,
        7.63555914e-02, -2.64719911e-02, -2.48515829e-02, -6.21011183e-02,
        2.41339114e-03,  1.35651110e-02, -2.10072603e-02,  1.08263167e-02,
       -2.59474702e-02,  1.11865610e-01, -8.04560632e-02,  3.25922333e-02,
       -4.19933684e-02, -1.04573639e-02,  3.15188691e-02,  2.54061110e-02,
       -2.09770240e-02, -2.18281131e-02, -5.46535030e-02,  1.85963772e-02,
        1.67466905e-02,  3.33932713e-02, -2.05906630e-02, -3.68540660e-02,
       -2.19426001e-03,  2.53356318e-03, -7.76289031e-03, -1.50252990e-02,
        6.98362440e-02, -4.96411920e-02, -2.84476690e-02,  7.35764429e-02,
       -3.88507661e-03, -4.20566723e-02, -6.32228777e-02,  3.00887655e-02,
       -1.79308858e-02,  1.62704196e-02, -5.61013911e-03, -4.16613696e-03,
       -3.73859657e-03,  1.53450556e-02,  5.60708530e-02,  8.47472250e-03,
        2.47359667e-02,  5.88313229e-02,  2.40103826e-02, -1.02473777e-02,
       -5.44886179e-02,  5.74777126e-02, -3.96610908e-02,  5.39208986e-02,
        4.32297327e-02, -2.76133809e-02,  7.75652099e-03,  1.28315212e-02,
        3.41419247e-03, -1.39486487e-03, -5.90689033e-02,  3.52379717e-02,
       -3.83809619e-02,  2.45056972e-02,  1.27516463e-02, -9.91710741e-03,
       -1.95557121e-02,  4.46337909e-02,  3.88993993e-02,  3.97662483e-02,
        7.28781074e-02, -4.71323282e-02, -4.68343049e-02, -1.49064139e-03,
       -6.70622215e-02, -1.75173283e-02,  6.73409253e-02, -4.13175039e-02,
        4.33900543e-02, -6.63495390e-03, -5.37491143e-02, -7.48066828e-02,
       -8.31445039e-04,  3.41901230e-03,  4.71801031e-03,  2.95769721e-02,
        4.71180910e-03, -2.88756955e-02, -4.25979719e-02,  1.68761276e-02,
       -4.80891112e-03,  1.72957312e-02, -3.84165859e-03, -4.17625904e-02,
        1.44476956e-02,  5.06875329e-02, -3.23178880e-02, -9.27965436e-03,
       -1.67109296e-02, -3.72978672e-02, -8.80808104e-03,  1.02387061e-02,
        1.31808398e-02, -4.96375225e-02, -2.98122130e-03, -2.97359563e-02,
        3.11158281e-02, -3.57207954e-02, -3.37390415e-02, -3.02072559e-02,
        6.78711710e-03,  3.77031416e-02,  6.36205003e-02,  4.43532206e-02,
        2.08181869e-02,  1.44333756e-02,  6.78439811e-03, -2.14169067e-05,
       -4.81526330e-02, -7.88310990e-02,  2.58551165e-02,  2.00299658e-02,
       -6.03759214e-02, -5.90742789e-02, -2.35881042e-02, -3.46442275e-02,
        7.35218450e-03, -1.35419685e-02, -1.02136144e-02,  4.41174321e-02,
       -2.66699772e-02, -3.51068154e-02, -4.14173976e-02,  4.18760218e-02,
       -3.77439745e-02, -1.72556378e-03,  1.45911621e-02, -7.26189464e-03,
       -5.69594391e-02,  4.33994737e-03,  3.31316553e-02, -3.90356742e-02,
        8.05978756e-03, -1.28872683e-02,  6.39529824e-02,  2.06201617e-02,
       -6.93183485e-03,  7.25929588e-02,  7.94036686e-03,  2.59195045e-02,
       -5.31743169e-02,  2.15033554e-02,  4.98494580e-02,  2.60427296e-02,
       -9.49478336e-03,  1.05583509e-02, -1.10148769e-02, -1.13412160e-02,
        1.18698422e-02, -4.88514788e-02, -7.00676860e-03,  1.56430732e-02,
       -5.82602359e-02,  5.66792227e-02,  3.06800064e-02, -4.26435703e-03,
       -4.70775664e-02,  5.07534808e-03,  2.24697273e-02, -1.15441205e-02,
       -1.22546824e-02, -1.03909494e-02,  1.09887812e-02,  3.26023549e-02,
       -2.95653790e-02, -1.41024636e-02,  2.55116392e-02, -3.66440713e-02,
        1.91083476e-02, -4.62679863e-02,  3.99200767e-02, -1.99659895e-02,
       -1.72185805e-02,  4.88742590e-02, -1.93238948e-02, -7.68593103e-02,
        4.27372865e-02,  1.20283756e-02,  2.67307870e-02, -1.30291097e-02,
        5.52635128e-03, -8.37767404e-03, -2.95357611e-02,  2.23877877e-02,
        1.52632408e-02, -6.93941349e-03, -3.85081582e-02, -1.18642775e-02],
      dtype=float32), array([-2.02811491e-02, -2.13170750e-03, -3.35631110e-02,  8.09577033e-02,
       -2.32375450e-02, -2.60246322e-02,  4.21737656e-02, -6.73021190e-03,
       -1.93272326e-02,  1.35891223e-02, -8.86976160e-03, -2.88219545e-02,
        1.27498060e-04,  5.68412840e-02,  2.38957088e-02, -4.67315912e-02,
       -7.16377124e-02,  3.80956978e-02,  7.19674630e-03, -1.99118778e-02,
       -2.96412199e-03,  4.28159237e-02, -7.36197829e-02,  2.44991817e-02,
       -1.09784249e-02,  1.95493214e-02, -5.16993813e-02, -4.47999239e-02,
       -2.60614157e-02, -6.87255636e-02, -8.74313153e-03,  2.89548300e-02,
        5.75069636e-02, -1.82986390e-02, -7.28606582e-02,  5.20225661e-03,
       -2.08781455e-02,  4.57101166e-02,  1.79318991e-02, -5.07986322e-02,
       -9.16864797e-02,  5.20711578e-02, -2.84199370e-03, -4.28686738e-02,
        2.06378754e-03,  1.64495129e-02, -7.06106192e-04,  3.31614055e-02,
        1.96389928e-02, -1.56299304e-02, -4.90196981e-03,  6.81547374e-02,
        2.71808431e-02,  1.07139265e-02,  2.35711061e-03, -4.34144437e-02,
        4.38811667e-02, -1.44843513e-03, -3.10690552e-02, -7.09699392e-02,
       -8.53438582e-03,  1.11895083e-02,  5.01731150e-02, -7.33345672e-02,
        1.05260557e-03, -1.61611307e-02, -2.83309426e-02, -2.00152639e-02,
        1.47782303e-02,  7.92450532e-02, -4.17209566e-02,  1.14251133e-02,
        1.82086602e-03,  9.11363959e-03,  5.21184504e-02,  8.44144076e-03,
        2.64309201e-05, -7.83608761e-03, -4.55393121e-02,  1.87891722e-02,
        8.27421341e-03,  6.18219450e-02,  9.59062576e-03,  6.85084611e-03,
       -3.56185399e-02,  4.06854115e-02,  5.49270026e-02, -4.53330390e-02,
       -6.53511435e-02, -3.85914259e-02, -2.05843002e-02,  4.27005775e-02,
       -4.82467841e-03,  6.60459101e-02,  4.74293530e-02,  7.44015127e-02,
        2.30318941e-02, -7.31618106e-02, -2.99427821e-03,  8.99057835e-03,
       -1.40856868e-02, -5.22432402e-02,  1.23102916e-02, -9.65682641e-02,
       -4.25434522e-02, -5.34251146e-02, -2.63475999e-02,  8.41043424e-03,
       -3.18382792e-02, -1.46785667e-02,  3.98131162e-02,  7.23841542e-04,
       -3.20551321e-02, -4.38806936e-02, -2.35775206e-02, -2.00976506e-02,
        4.23264392e-02, -3.10586374e-02, -8.52883235e-02,  2.23898441e-02,
       -9.51789320e-02, -1.41135231e-02,  3.01965270e-02,  5.90272658e-02,
       -6.14715740e-02, -2.81729419e-02, -1.46777155e-02, -2.56582107e-02,
        2.41008494e-02, -7.58688059e-03,  7.28762448e-02, -1.95540115e-02,
        4.08979766e-02,  2.28580888e-02, -1.06551889e-02,  3.21902111e-02,
        8.42889324e-02,  4.67495769e-02, -2.24730615e-02, -3.59596834e-02,
       -1.43541796e-02,  7.55053833e-02,  3.95209379e-02,  3.88102536e-03,
        8.74332711e-02,  5.44265807e-02,  1.07341167e-02, -2.95079146e-02,
       -5.25210984e-02,  1.78374629e-02, -4.03523035e-02, -3.59334722e-02,
       -6.56711534e-02, -3.15298289e-02, -1.69566518e-03,  8.95500928e-03,
        1.13807796e-02,  5.10735102e-02,  4.44714352e-03, -4.04468067e-02,
       -6.91634510e-03,  2.28644498e-02,  3.52351889e-02,  1.73912309e-02,
       -5.67583106e-02, -1.08825490e-02, -9.90466103e-02,  4.07281443e-02,
        2.64071720e-03,  1.24192135e-02,  6.31342605e-02, -4.55391826e-03,
        4.59607765e-02, -5.81790553e-03, -5.38491569e-02, -1.88461468e-02,
       -2.13577636e-02,  6.20024512e-04, -1.89676266e-02,  6.75715953e-02,
        5.28975530e-03, -6.44278750e-02,  3.28336135e-02, -2.28484441e-02,
        2.87722722e-02, -8.45151488e-04,  5.57360053e-02, -2.82614529e-02,
        3.21902595e-02, -1.36388429e-02, -4.73567285e-02, -3.26486491e-02,
        2.51841522e-03,  7.14228675e-02, -4.93624844e-02,  2.01068819e-02,
       -2.07995139e-02, -4.77596931e-02, -2.45137941e-02,  6.31450266e-02,
        2.47637983e-02,  7.36109242e-02, -6.23466261e-02,  2.78400388e-02,
       -6.87856693e-03, -4.57506217e-02,  4.95844241e-03, -5.10438606e-02,
       -3.18917483e-02,  1.30163403e-02,  5.90234213e-02, -9.45500657e-03,
        5.91174467e-03,  2.05696020e-02, -5.16229169e-03,  7.44262189e-02,
        5.24902083e-02, -3.03929765e-02,  4.38887179e-02, -6.30745962e-02,
        3.69580202e-02, -3.09756994e-02, -1.26132974e-02,  4.19253334e-02,
        2.16656439e-02, -6.26953915e-02,  1.34131229e-02, -1.58218027e-03,
        1.48208952e-02, -4.48324308e-02,  2.24905480e-02,  3.38689014e-02,
        1.90136228e-02, -1.23666422e-02, -6.65514544e-02,  1.22220637e-02,
       -9.42253042e-03,  6.88806251e-02,  5.80225028e-02, -5.00708446e-02,
        1.30619351e-02, -6.91489503e-02, -5.72755672e-02,  1.32428510e-02,
       -2.98984442e-02,  3.01267896e-02,  5.80116026e-02, -1.77786965e-02,
        1.43971611e-02,  4.00832593e-02, -4.27243412e-02, -7.03333914e-02,
       -1.13966186e-02,  7.15093091e-02,  4.84014116e-02,  4.42830697e-02,
       -5.52121066e-02, -2.71467306e-03,  5.38166128e-02, -3.50763462e-02,
       -2.60343757e-02,  4.32797037e-02,  2.62803119e-02, -3.46521623e-02,
       -1.12745054e-02,  1.55743165e-02, -9.31206066e-03, -2.05914602e-02,
        1.97251886e-02,  4.64330576e-02,  3.64135616e-02, -4.44528237e-02,
       -6.79096133e-02,  3.16135697e-02,  9.00685415e-02,  9.97635536e-03,
       -1.94181805e-03,  3.13530266e-02, -3.11998476e-04,  9.44079086e-02,
        3.68398726e-02, -9.59994122e-02, -6.10367544e-02, -5.78605272e-02,
       -2.88180225e-02,  6.92729056e-02, -3.53644602e-02, -2.06222031e-02,
       -3.39346230e-02,  5.70239276e-02,  3.49947549e-02, -3.82064097e-02,
        5.53409830e-02,  2.02257317e-02, -8.00529495e-02, -5.51774092e-02,
       -5.95014393e-02, -4.70308326e-02, -1.02483034e-02,  3.23312776e-03,
       -3.87986973e-02,  2.95440550e-04,  9.52173620e-02,  4.21991684e-02,
        4.17916477e-02, -1.17204878e-02, -5.34185618e-02,  3.16814929e-02,
        1.28406752e-03, -4.50267196e-02, -1.12667168e-02,  8.70920569e-02,
        6.28662109e-02,  6.70276508e-02, -1.97061449e-02,  3.40679288e-02,
        2.66773868e-02, -5.56870215e-02, -4.51923236e-02,  6.65577427e-02,
       -3.23003232e-02,  3.86182666e-02,  3.23885232e-02, -9.89394262e-03,
        1.46605941e-02, -7.13136606e-03, -2.60174721e-02, -6.93736374e-02,
       -2.61086617e-02, -1.96627667e-03, -1.35757774e-02,  2.14618593e-02,
       -2.76503013e-03,  2.29374338e-02, -9.72786993e-02, -1.33544793e-02,
       -1.05763031e-02, -5.29509075e-02,  3.01553570e-02, -8.23818818e-02,
        3.37567888e-02,  4.42847349e-02,  9.59012751e-03, -4.89323139e-02,
        3.31159309e-02, -4.96588387e-02, -3.86335477e-02,  2.19603926e-02,
        6.24846295e-03, -2.43825223e-02, -6.38477802e-02,  2.65385490e-02,
       -2.13850029e-02,  9.64613352e-03,  5.74988723e-02,  4.88521270e-02,
       -5.93070015e-02, -1.57873419e-05,  5.13966903e-02,  4.95954566e-02,
       -1.97317638e-02,  2.43901741e-02,  7.26410672e-02,  4.25498411e-02,
       -3.85005698e-02,  2.99140364e-02, -1.57613885e-02,  1.95874386e-02,
        2.60605030e-02, -4.63489853e-02,  6.75394908e-02,  2.23636348e-02,
        5.03678024e-02, -1.61069464e-02, -5.41850105e-02,  5.23286546e-03,
       -6.27851784e-02,  3.91600616e-02, -1.90294404e-02, -1.61205046e-02,
        3.65098007e-02, -1.51123691e-04,  4.75657359e-02,  2.69147400e-02,
       -3.63704772e-03,  9.00666136e-03, -2.46112198e-02, -5.07888682e-02,
        1.38633614e-02,  6.87797964e-02, -1.01914639e-02, -9.45692658e-02,
        8.65550116e-02, -1.58575363e-02, -6.17336892e-02,  5.01942672e-02,
       -5.92379160e-02, -6.94782799e-03, -2.03231280e-03,  8.69542127e-04,
       -1.14519056e-02, -5.03364690e-02, -6.34776950e-02, -1.05187958e-02,
        1.76664721e-02,  3.92478369e-02, -1.82734821e-02,  4.76643927e-02,
       -7.20027462e-02,  1.01719713e-02, -4.00359631e-02, -6.20435516e-04,
        4.72720377e-02,  3.21775698e-03,  1.18610477e-02,  3.34163010e-02,
        3.36589641e-03, -1.76089145e-02, -1.88747104e-02,  1.55295767e-02,
       -5.99580705e-02, -4.49803732e-02, -3.92681174e-03, -4.57793847e-02,
        1.23794666e-02,  2.02788990e-02,  6.89409580e-03,  9.30005610e-02,
        4.49542068e-02,  1.01298625e-02,  3.03246211e-02, -6.38467893e-02,
       -5.92312105e-02, -6.19920343e-02, -2.57531460e-02,  1.44712012e-02,
       -7.49317333e-02, -2.39032488e-02,  4.40388508e-02, -3.39579657e-02,
        3.43844630e-02,  1.89899784e-02, -5.07500283e-02,  3.24012600e-02,
        7.34532299e-03, -4.01342586e-02, -5.05843274e-02,  5.94118685e-02,
       -5.33369109e-02, -1.17137535e-02,  5.55340608e-04,  5.36887832e-02,
       -5.53823672e-02, -4.08757664e-02, -1.65476575e-02, -1.11346945e-01,
        3.97689231e-02, -2.60727509e-04,  1.09490842e-01,  5.45589440e-02,
       -4.60199304e-02,  5.02045304e-02,  1.34744467e-02,  7.97252264e-03,
        1.39324169e-03,  7.64167607e-02,  4.01051482e-03,  6.94261342e-02,
        1.32025778e-02,  3.02695041e-03, -5.43815829e-02, -2.06643157e-02,
       -2.27363482e-02, -4.20801230e-02, -1.03561766e-02, -9.08897966e-02,
       -8.77058133e-02, -2.15350725e-02,  8.04276764e-02,  2.28484236e-02,
       -5.57997599e-02, -1.81105677e-02,  2.04128735e-02, -1.25994831e-02,
        3.38755432e-03, -5.82076460e-02,  1.33644817e-02,  1.26328068e-02,
       -6.76728413e-03,  2.78590322e-02,  2.54477225e-02, -4.05439129e-03,
        5.98457903e-02,  2.41523627e-02, -1.30579313e-02, -4.08186540e-02,
        4.65360470e-02,  5.51772751e-02,  2.63032112e-02, -2.22556610e-02,
        5.06087057e-02,  3.29433456e-02,  1.01491492e-02,  5.27297407e-02,
       -4.35601324e-02,  5.35457022e-03,  1.20928213e-02, -2.07423400e-02,
        3.52493674e-02, -1.52688976e-02, -3.79307941e-02, -1.51234902e-02],
      dtype=float32), array([-6.01384649e-03, -1.92484837e-02, -5.51651567e-02,  5.40646091e-02,
        1.40186241e-02, -1.03244046e-02,  2.37559341e-02,  8.75774212e-03,
       -2.57752109e-02,  4.06828970e-02, -1.18468432e-02, -2.04642415e-02,
        5.02975807e-02, -1.38487909e-02,  1.11067947e-02,  2.12895963e-02,
       -9.10608470e-02, -1.93416532e-02,  3.37222964e-02, -1.82776153e-02,
        3.83205246e-04,  7.86913633e-02, -4.29273322e-02,  3.94890979e-02,
        2.66935509e-02,  6.55675977e-02, -3.00488882e-02, -7.58209899e-02,
        3.57351527e-02, -3.02042961e-02, -1.04781426e-03,  4.08989489e-02,
        2.28130426e-02, -2.75970120e-02,  1.56944580e-02,  2.50681862e-02,
        5.76119535e-02, -1.07724220e-02,  1.05499234e-02, -2.85909120e-02,
       -4.00062837e-02, -8.72826390e-03,  4.33034301e-02, -4.60114963e-02,
       -1.40394270e-02,  2.68892515e-02, -4.64897268e-02,  6.61424920e-03,
       -1.13255158e-02,  4.07533422e-02,  3.79096530e-02, -4.71914597e-02,
       -4.26531490e-03,  1.32519165e-02, -5.13259228e-03, -5.65860458e-02,
        6.27468675e-02, -6.83343969e-03, -2.22242568e-02, -9.65588633e-03,
        7.15635270e-02,  2.42185742e-02,  3.16896150e-03, -6.12139031e-02,
       -6.62472695e-02, -1.36383455e-02,  1.34022348e-02, -8.42199661e-03,
        3.22942398e-02,  6.03940785e-02,  6.41118921e-03, -1.31168738e-02,
       -2.78999959e-03,  6.00808114e-02,  2.97250766e-02,  1.31933885e-02,
       -1.35337301e-02,  3.09195165e-02, -3.83132435e-02,  8.71825032e-04,
        6.32305071e-02,  2.73564346e-02, -6.38299203e-03, -4.75058071e-02,
       -5.37473150e-02, -2.34303996e-02,  2.00537723e-02, -1.10485242e-03,
       -2.00410392e-02, -3.79512496e-02,  3.85155082e-02,  2.80834567e-02,
        9.67943110e-03,  5.23674004e-02,  4.87278439e-02,  5.11221439e-02,
        4.12806608e-02, -8.00781697e-02, -1.01857513e-01,  6.54005632e-02,
       -4.23826315e-02, -6.30806014e-02,  6.99526221e-02, -5.43463677e-02,
       -9.27553177e-02, -8.43560472e-02, -2.80810185e-02, -5.06078638e-02,
       -3.21104825e-02,  1.42321587e-02,  2.55799796e-02, -1.87432859e-04,
       -3.91920935e-03, -4.14081514e-02,  2.80565564e-02, -6.68688342e-02,
        1.57106910e-02,  1.24598620e-04, -4.42491919e-02,  5.33420742e-02,
       -1.75585523e-02,  2.75816545e-02,  4.93503409e-03, -2.67759357e-02,
       -4.86741029e-02, -6.57303119e-03, -5.32734692e-02, -1.47412680e-02,
        4.80997637e-02,  2.84873880e-02,  8.78025144e-02, -5.89530617e-02,
        1.92309031e-03,  2.95451302e-02, -7.10565746e-02,  3.13002244e-02,
        5.86791672e-02,  5.68828285e-02,  2.07611881e-02,  1.90041140e-02,
       -1.97391119e-02,  9.10822302e-04,  3.72809023e-02, -1.08658522e-02,
        4.87285331e-02,  4.47778292e-02,  1.35726556e-02, -2.01220457e-02,
        3.22201848e-02, -5.38939610e-02,  2.02258234e-04,  1.19198430e-02,
       -5.08295856e-02, -3.10581699e-02,  1.53693976e-02, -4.85303998e-02,
       -7.29845613e-02,  8.68650451e-02,  1.18344380e-02,  7.73771387e-03,
       -5.20407334e-02, -4.95696105e-02,  1.50634293e-02,  1.94263011e-02,
       -3.69042810e-03, -2.08445452e-02, -5.26392087e-02, -2.58092768e-02,
        5.14834598e-02,  1.63852405e-02,  2.55954601e-02, -1.67395547e-02,
        4.03340161e-02,  4.19402942e-02,  4.63312864e-02, -3.39735895e-02,
        2.94515882e-02,  2.29442175e-02, -1.84308346e-02,  5.48505504e-03,
       -7.69413263e-02, -1.31052211e-02, -2.37377919e-02, -6.99995607e-02,
       -3.35067250e-02, -6.39851252e-03,  9.47951078e-02, -4.66358811e-02,
       -6.42046658e-03, -5.30586625e-03,  9.52593749e-04,  3.84359574e-03,
        9.05384347e-02,  4.48074974e-02, -5.73883466e-02, -2.85181752e-03,
       -1.05011277e-04,  6.20982377e-03, -9.38982423e-03,  2.15443894e-02,
        5.26284706e-03,  4.50341552e-02, -7.66181294e-03,  4.19548750e-02,
        2.62782676e-03,  1.07089188e-02,  7.85717219e-02, -2.89273765e-02,
       -4.67888154e-02, -1.40768960e-02, -3.51471896e-03, -3.67924869e-02,
       -2.21849792e-02,  8.52214545e-02,  7.21807033e-02,  6.24481030e-02,
        2.31364816e-02, -6.15351908e-02,  1.12044262e-02, -2.07020491e-02,
       -7.18584284e-03, -4.76721413e-02, -2.47442108e-02,  2.14133300e-02,
       -4.54445183e-03, -6.10190704e-02, -2.33295746e-03, -3.95953506e-02,
        2.81475112e-02,  1.92335024e-02,  4.20969725e-02,  6.61861151e-02,
        1.98335219e-02, -9.03166831e-03, -6.81908056e-02,  3.82832587e-02,
       -3.31596211e-02,  5.89993671e-02,  1.79705536e-03, -5.17815128e-02,
       -4.88523208e-02,  2.37039924e-02, -1.57265458e-02,  2.51328144e-02,
        1.21307177e-02,  1.29038729e-02,  6.74183220e-02, -9.09384154e-03,
        3.12230960e-02,  6.95408210e-02, -5.25108874e-02, -5.61733581e-02,
       -5.27393557e-02,  6.31324155e-03, -1.41665665e-03, -4.06689756e-02,
       -4.45734262e-02, -2.51643080e-02,  2.97723785e-02, -1.24192452e-02,
       -1.78674925e-02,  1.08646676e-02, -1.98218636e-02, -8.29979926e-02,
       -5.59820468e-03, -4.40285467e-02, -3.62726301e-02,  2.63344683e-02,
       -3.71194296e-02, -2.75497437e-02,  7.47981668e-02, -4.24544839e-03,
       -2.28990335e-02,  7.45853186e-02,  3.37979533e-02, -3.95245850e-03,
        4.52023447e-02,  4.20798883e-02,  1.85717549e-03,  7.60162100e-02,
        1.97107270e-02, -1.14115840e-02, -4.65732701e-02, -5.78094646e-02,
       -3.03049777e-02, -3.46580446e-02, -3.48469093e-02, -3.90246287e-02,
       -3.86807993e-02,  4.61935066e-02, -1.82796437e-02, -5.65975998e-03,
       -2.37511247e-02,  6.83166012e-02, -4.92899045e-02, -3.22548784e-02,
       -2.32606567e-02, -2.18113661e-02, -6.26409277e-02,  4.43685539e-02,
       -4.31736978e-03, -1.29560288e-02,  7.95250684e-02,  5.08795530e-02,
       -6.81216968e-03, -7.64141604e-03, -4.97937687e-02,  4.29192297e-02,
        1.11627835e-03,  4.94083390e-04,  1.31939789e-02,  7.20468014e-02,
        4.80609722e-02,  6.25400990e-02, -2.35308409e-02,  5.93225323e-02,
        3.45867351e-02, -6.30162507e-02, -1.31176803e-02, -1.35122817e-02,
        3.37304547e-02, -1.63360517e-02, -3.50176916e-02, -1.55940512e-03,
       -1.29930191e-02,  5.86488172e-02, -2.42266655e-02, -3.74319814e-02,
       -7.31515437e-02, -1.62592381e-02,  5.84626570e-02, -9.15223453e-03,
       -1.51124243e-02, -1.16147269e-02, -6.85264319e-02, -1.69292241e-02,
       -4.13226373e-02, -1.48805808e-02,  3.02574970e-02, -3.09688430e-02,
        5.82794584e-02,  2.15386003e-02,  2.65182480e-02, -4.30297367e-02,
        6.87909648e-02, -8.28883871e-02, -6.25053123e-02, -6.96669333e-03,
       -1.34296659e-02, -1.24623105e-02, -8.25602785e-02,  8.55977461e-03,
       -5.98732978e-02,  5.10066599e-02, -2.53873616e-02,  3.99908498e-02,
        4.61594611e-02,  3.09622264e-04,  5.35629317e-02, -1.82262156e-02,
        1.74925048e-02,  1.57472771e-02,  3.67249548e-02,  2.44455785e-02,
       -1.48499198e-02,  1.25693912e-02, -2.57812738e-02,  3.82372811e-02,
       -3.09055895e-02, -1.29485317e-02,  7.01338947e-02,  2.61746142e-02,
       -6.27597347e-02, -3.38786803e-02, -5.91590628e-02,  7.63139315e-03,
       -1.27291335e-02, -8.74094665e-04,  2.21978649e-02, -4.29675058e-02,
        2.47407109e-02,  2.65569612e-02,  1.08815603e-01,  1.07279816e-03,
        2.53589656e-02, -3.98790315e-02, -9.44732726e-02, -5.29406667e-02,
       -7.31511191e-02,  6.62015658e-03,  9.50518101e-02, -6.20236881e-02,
        5.68643920e-02, -4.44344878e-02, -2.91555398e-03, -2.57707648e-02,
        2.41707265e-02,  7.20629022e-02, -1.76332183e-02,  4.10007797e-02,
       -3.62618268e-02, -1.06061716e-02, -3.36494371e-02,  6.93702102e-02,
       -2.03945953e-02, -5.10316994e-03,  1.48037393e-02,  5.66647947e-03,
       -5.65797230e-03,  3.32099423e-02,  1.50385574e-02, -2.87287738e-02,
        1.07750967e-02, -5.02188914e-02,  3.92911732e-02,  1.45945337e-03,
        4.81794355e-03, -2.97365747e-02,  3.37128597e-03, -7.32078403e-03,
       -5.53672835e-02, -2.87130959e-02,  1.46534359e-02, -4.48318161e-02,
       -2.99089234e-02,  8.84607881e-02,  7.11780861e-02,  7.71143511e-02,
        3.56732495e-03,  1.67724714e-02,  5.61842769e-02,  3.75255309e-02,
       -7.75211006e-02, -4.01084274e-02,  4.90343869e-02,  4.57397178e-02,
        1.56181669e-02, -3.02548707e-02,  1.07989470e-02,  1.97995687e-03,
       -9.16204788e-03, -3.55592258e-02, -7.68482834e-02,  3.37525234e-02,
       -2.67569683e-02, -2.90539302e-02, -7.02774823e-02,  6.35570288e-02,
        7.01851863e-03, -4.02769893e-02,  2.67710239e-02, -1.21943792e-02,
       -1.00914873e-01, -9.03750397e-03,  3.03717889e-02, -3.03738285e-03,
       -1.25042852e-02, -3.16933878e-02,  1.14118364e-02,  5.23015037e-02,
       -4.35300805e-02,  1.35396291e-02, -4.22535092e-03,  7.98219740e-02,
       -3.66361327e-02, -9.19072074e-04,  2.23926697e-02,  5.76953311e-03,
       -2.50775926e-02, -3.10378820e-02,  2.87654568e-02,  1.04038473e-02,
        7.11981487e-03, -2.17593126e-02,  7.05462880e-04,  5.83144510e-03,
       -6.75205439e-02, -9.53566656e-03,  3.41723561e-02,  3.26014236e-02,
       -6.09209687e-02, -8.37454014e-03,  6.73034489e-02,  3.11452355e-02,
       -2.86608245e-02, -6.97626621e-02, -5.50635085e-02,  3.26072797e-02,
       -6.65015131e-02, -9.63154715e-04,  3.12062576e-02, -1.03936912e-02,
        4.87413891e-02, -7.43136406e-02,  6.17741607e-02, -5.26226731e-03,
        3.17284577e-02,  3.35884839e-02,  2.52700411e-04, -4.49868739e-02,
        9.48661938e-02,  1.07525848e-03,  4.60257083e-02, -2.69449092e-02,
       -4.56407107e-03,  3.21266539e-02, -2.80161873e-02, -2.39471830e-02,
        2.41921842e-03,  1.80876516e-02, -1.26101123e-02, -2.69059576e-02],
      dtype=float32)] to be a dense tensor with shape [3], but got shape [3, 512].

In [1]:
import tensorflow.compat.v1 as tf
import cv2
import os
import numpy as np

tf.disable_v2_behavior()

# Load FaceNet model
with tf.gfile.GFile('20180402-114759.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

graph = tf.Graph()
with graph.as_default():
    tf.import_graph_def(graph_def, name='')
    session = tf.compat.v1.Session(graph=graph)

images_input = graph.get_tensor_by_name("input:0")
embeddings_output = graph.get_tensor_by_name("embeddings:0")
phase_train = graph.get_tensor_by_name("phase_train:0")

def load_image(file_path):
    img = cv2.imread(file_path)
    if img is None:
        raise ValueError(f"Could not load image at {file_path}")
    return img

def get_embedding(img):
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = (img / 255.0 - 0.5) * 2.0  
    img = np.expand_dims(img, axis=0)
    embedding = session.run(embeddings_output, feed_dict={
        images_input: img,
        phase_train: False
    })
    print(f"Embedding: {embedding[0][:5]}...")  
    return embedding[0]

def create_embedding(folder_path):
    embeddings = []
    for person in os.listdir(folder_path):
        person_path = os.path.join(folder_path, person)
        print(f"Person path: {person_path}")
        if os.path.isdir(person_path):
            person_embedding = []
            for photo in os.listdir(person_path):
                photo_path = os.path.join(person_path, photo)
                print(f"Photo path: {photo_path}")
                try:
                    img = load_image(photo_path)
                    embedding = get_embedding(img)
                    person_embedding.append(embedding)
                except Exception as e:
                    print(f"Failed to process {photo_path}: {e}")
            if person_embedding:
                avg_embedding = np.mean(person_embedding, axis=0)
                embeddings.append(avg_embedding)
                print(f"Embedding created for {embeddings}")
    np.save('embeddings',embeddings)
    return embeddings

folder_path = 'Tdataset'
embeddings_output = create_embedding(folder_path)
# print(f"Total persons with embeddings: {len(embeddings_output)}")
# for i, emb in enumerate(embeddings_output):
#     print(f"Person {i} embedding: {emb[:5]}... (shape: {emb.shape})")

2025-03-11 19:29:32.805631: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-11 19:29:37.089224: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-11 19:29:37.097025: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-11 19:29:46.353634: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Instructions for updating:
non-resource variables are not supported in the long term
Person path: Tdataset/jafer
Photo path: Tdataset/jafer/20240419_174558_face5.jpg


2025-03-11 19:30:12.442264: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled


Embedding: [ 0.03580908 -0.05763133 -0.08140878  0.0035108  -0.03590025]...
Photo path: Tdataset/jafer/20240419_174916_face3008.jpg
Embedding: [ 0.03418978 -0.05238625 -0.07633385  0.01750444 -0.01756687]...
Photo path: Tdataset/jafer/20240419_173538_face3005.jpg
Embedding: [ 0.03601177 -0.04103716 -0.08305649  0.0248758  -0.02792012]...
Photo path: Tdataset/jafer/20240419_174628_face3011.jpg
Embedding: [ 0.00662687 -0.03014959 -0.06662046  0.00259472 -0.01090813]...
Photo path: Tdataset/jafer/20240419_174922(1)_face3002.jpg
Embedding: [ 0.04193246 -0.03886791 -0.06907566  0.01082498 -0.03305881]...
Photo path: Tdataset/jafer/20240419_180050_face8.jpg
Embedding: [ 0.06064612 -0.03740379 -0.04390897  0.0353514  -0.00887452]...
Photo path: Tdataset/jafer/20240419_173512_face3008.jpg
Embedding: [ 0.03409502 -0.03872005 -0.07723562  0.00251468 -0.01122557]...
Photo path: Tdataset/jafer/20240419_174634_face3011.jpg
Embedding: [ 0.01073835 -0.0118688  -0.10377845  0.04704848  0.01157974]...


In [ ]:
# def verify_live_cam(present_embeddings):
#     cap = cv2.VideoCapture(0)  # Open webcam
#     face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    
#     while True:
#         ret, frame = cap.read()  # Get frame
#         if not ret:
#             print("Failed to access webcam")
#             break
#         frame=cv2.imread('Tdataset/feleke/photo_5933665171497141373_y_face3000.jpg')
#         faces= cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#         faces=cv2.resize(gray,160,160)
#        # faces = face_detector.detectMultiScale(gray, 1.1, 5)
        
#         for (x, y, w, h) in faces:
#             face = frame[y:y+h, x:x+w]
#             claim_embedding = get_embedding(face)
            
#             # Compare to present embeddings
#             min_dist = 100
#             for present_embedding in present_embeddings:
#                 dist = np.linalg.norm(claim_embedding - present_embedding)
#                 if dist < min_dist:
#                     min_dist = dist
            
#                     if min_dist < 1.2:
#                         print("Present") 
#                     else:
#                         print("Not Present")
#     #         cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
#     #         cv2.putText(frame, result, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
        
#     #     cv2.imshow("Party Verification", frame)
#     #     if cv2.waitKey(1) == ord('q'):  # Quit with 'q'
#     #         break
    
#     # cap.release()
#     # cv2.destroyAllWindows()

# # Run the full system
# present_folder = 'Tdataset'
# present_embeddings = create_embedding(present_folder)
# print(f"Total embeddings: {len(present_embeddings)}")
# verify_live_cam(present_embeddings)

Person path: Tdataset/abel gezu
Photo path: Tdataset/abel gezu/IMG_8142_face3002.jpg
Embedding: [-0.02462943 -0.00477117 -0.0383881   0.0877642  -0.01053893]...
Photo path: Tdataset/abel gezu/IMG_8239_face3000.jpg
Embedding: [-0.02308235  0.00312175 -0.01736182  0.09786963 -0.03550561]...
Photo path: Tdataset/abel gezu/20240419_175057_face2.jpg
Embedding: [ 0.00213678  0.00829811 -0.02545333  0.09006491 -0.02246968]...
Photo path: Tdataset/abel gezu/IMG_8240_face3001.jpg
Embedding: [-0.01958076 -0.00600055 -0.01625586  0.09367585 -0.02452578]...
Photo path: Tdataset/abel gezu/IMG_8140_face3000.jpg
Embedding: [-0.02613613 -0.0036355  -0.03253046  0.07849814 -0.00544161]...
Photo path: Tdataset/abel gezu/IMG_8137_face3001.jpg
Embedding: [-0.01857939  0.00402282 -0.02382888  0.09365387 -0.02437561]...
Photo path: Tdataset/abel gezu/IMG_8139_face3000.jpg
Embedding: [-0.01521372  0.0060447  -0.02943036  0.09547939 -0.01070167]...
Photo path: Tdataset/abel gezu/IMG_7945_face3000.jpg
Embeddin

[ WARN:0@1561.832] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1561.895] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range


Failed to access webcam


In [ ]:
def verify_image(image_path,present_embeddings):
    frame = cv2.imread(image_path)
    if frame is None:
        print(f"Failed to load image: {image_path}")
        return
    
    # Assuming image is already 160x160 cropped face
    claim_embedding= get_embedding(frame)
    print(claim_embedding)
    # Compare to present embeddings
    min_dist = float('inf')
    for i,present_embedding in enumerate(present_embeddings):
        dist = np.linalg.norm(claim_embedding - present_embedding)
        print(f'distance to embedding {i} is {dist}')
        if dist < min_dist:
            min_dist = dist
    
    result = "Present" if min_dist < 1 else "Not Present"
    print(f'minimum distanc {min_dist}')
    print(result)
    
   
    cv2.rectangle(frame, (0, 0), (160, 160), (0, 255, 0), 2)  
    cv2.putText(frame, result, (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
    cv2.imshow("Verification Result", frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


present_folder = 'Tdataset'
present_embeddings = create_embedding(present_folder)
print(f"Total embeddings: {len(present_embeddings)}")
image_path = ['Tdataset/cse keeper/photo_5841400108518850849_y_face3001.jpg',]

for i in image_path:
    verify_image(i, present_embeddings)


Person path: Tdataset/cse keeper
Photo path: Tdataset/cse keeper/jafer
Failed to process Tdataset/cse keeper/jafer: Could not load image at Tdataset/cse keeper/jafer
Photo path: Tdataset/cse keeper/20240419_174635_face14.jpg
Embedding: [-0.00442302 -0.06232953 -0.04689667  0.00096048 -0.01350463]...
Photo path: Tdataset/cse keeper/photo_5841400108518850851_y_face3001.jpg
Embedding: [ 0.0074398  -0.03755473 -0.08178994  0.03929864 -0.00201669]...
Photo path: Tdataset/cse keeper/20240419_173512_face3007.jpg
Embedding: [ 0.00945505 -0.0338832  -0.01541324  0.02714559 -0.04098909]...
Photo path: Tdataset/cse keeper/20240419_173534_face3001.jpg
Embedding: [-0.00126975  0.00988547 -0.00577551  0.01791202 -0.01747009]...
Photo path: Tdataset/cse keeper/20240419_173617_face3001.jpg
Embedding: [-0.00416346 -0.00953967 -0.00129011  0.00404144 -0.04389105]...
Photo path: Tdataset/cse keeper/20240419_174936_face3006.jpg
Embedding: [-0.00442971 -0.00229176 -0.03061895 -0.00638013 -0.04750886]...
Ph

In [3]:
present_folder = 'Tdataset'
present_embeddings = create_embedding(present_folder)

Person path: Tdataset/abel gezu
Photo path: Tdataset/abel gezu/IMG_8142_face3002.jpg


2025-03-11 02:23:25.186820: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled


Embedding: [-0.02462943 -0.00477117 -0.0383881   0.0877642  -0.01053893]...
Photo path: Tdataset/abel gezu/IMG_8239_face3000.jpg
Embedding: [-0.02308235  0.00312175 -0.01736182  0.09786963 -0.03550561]...
Photo path: Tdataset/abel gezu/20240419_175057_face2.jpg
Embedding: [ 0.00213678  0.00829811 -0.02545333  0.09006491 -0.02246968]...
Photo path: Tdataset/abel gezu/IMG_8240_face3001.jpg
Embedding: [-0.01958076 -0.00600055 -0.01625586  0.09367585 -0.02452578]...
Photo path: Tdataset/abel gezu/IMG_8140_face3000.jpg
Embedding: [-0.02613613 -0.0036355  -0.03253046  0.07849814 -0.00544161]...
Photo path: Tdataset/abel gezu/IMG_8137_face3001.jpg
Embedding: [-0.01857939  0.00402282 -0.02382888  0.09365387 -0.02437561]...
Photo path: Tdataset/abel gezu/IMG_8139_face3000.jpg
Embedding: [-0.01521372  0.0060447  -0.02943036  0.09547939 -0.01070167]...
Photo path: Tdataset/abel gezu/IMG_7945_face3000.jpg
Embedding: [-0.01338989 -0.02085176 -0.03149769  0.10350926 -0.00547501]...
Photo path: Tdata

In [6]:
x={'a':[]}
x['a'].append(1)
x

{'a': [1]}

Loading embedding where it saved

In [ ]:
def load_embedding(saved_path):
    if os.path.exists(saved_path):
        embedding=np.load(saved_path,allow_pickle=True).tolist()
        print(f'loaded embedding from {saved_path}')
        return embedding
    else:
        print(f'not saved embedding at {saved_path}')